// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HDD.Models
{
    public partial class RetrofitApplication
    {
        public RetrofitApplication()
        {
            VehicleDocuments = new HashSet<VehicleDocuments>();
        }

        public string Vin { get; set; }
        public int? EngineYear { get; set; }
        public string EngineManufacturer { get; set; }
        public string EngineFamilyNumber { get; set; }
        public string EngineDisplacement { get; set; }
        public string ArtFamilyName { get; set; }
        public string ApplicationDate { get; set; }
        public string RetrofitType { get; set; }
        public string RetrofitProvider { get; set; }
        public DateTime? RunDate { get; set; }
        public DateTime? EntryDateTime { get; set; }
        public string Comments { get; set; }

        public virtual ValidRetrofitProviders RetrofitProviderNavigation { get; set; }
        public virtual ValidRetrofitTypes RetrofitTypeNavigation { get; set; }
        public virtual Dmvccddata VinNavigation { get; set; }
        public virtual ICollection<VehicleDocuments> VehicleDocuments { get; set; }
    }
}