// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HDD.Models
{
    public partial class RetrofitCertification
    {
        public string Vin { get; set; }
        public string Vinstatus { get; set; }
        public string AgencyChanged { get; set; }
        public DateTime? ActionDate { get; set; }
        public string Certified { get; set; }
        public string ActionInspectorId { get; set; }
        public DateTime? EntryDateTime { get; set; }
        public string EntryUserId { get; set; }
        public string Comments { get; set; }

        public virtual ValidCertifiedTypes CertifiedNavigation { get; set; }
        public virtual Dmvccddata VinNavigation { get; set; }
    }
}