// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HDD.Models
{
    public partial class SecondaryOwnersAssignment
    {
        public string OwnerId { get; set; }
        public string Vin { get; set; }
        public string IncomingSecondaryOwnerEmail { get; set; }
        public DateTime? AssignedDate { get; set; }
        public bool? AssignmentCompleted { get; set; }

        public virtual Dmvccddata VinNavigation { get; set; }
    }
}