// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HDD.Models
{
    public partial class ValidRetrofitProviders
    {
        public ValidRetrofitProviders()
        {
            RetrofitApplication = new HashSet<RetrofitApplication>();
        }

        public string RetrofitProvoder { get; set; }
        public string Description { get; set; }
        public short? Sequence { get; set; }

        public virtual ICollection<RetrofitApplication> RetrofitApplication { get; set; }
    }
}